luisbocanegra/plasma-panel-colorizer

package/contents/config/main.xml
package/contents/ui/configWidgetBg.qml
package/contents/ui/main.qml

Add global widget horizontal/vertical margins
Per widget extra margins
Make padding grow with extra margins

Margins control to unify heights & extra margins for widgets

---

package/contents/config/main.xml
package/contents/ui/configForeground.qml
package/contents/ui/configGeneral.qml
package/contents/ui/configPanelBg.qml
package/contents/ui/configWidgetBg.qml
package/contents/ui/configWidgetBlacklist.qml
package/contents/ui/main.qml

https://github.com/luisbocanegra/plasma-panel-colorizer/issues/9

Presets management

---

CMakeLists.txt
install.sh
package/contents/ui/main.qml
plugin/CMakeLists.txt
plugin/panelcolorizer.cpp
plugin/panelcolorizer.h
plugin/panelcolorizerplugin.cpp
plugin/qmldir

Uses the custom background to update panelMask with correct rounded corners
https://github.com/luisbocanegra/plasma-panel-colorizer/issues/50

Make panel blur region follow custom panel background

---

README.md

I created a nix package for this widget. It is going to be available in nixos-unstable and nixpkgs-unstable in a few days.

Add nix package install methods

---

package/contents/config/config.qml
package/contents/ui/code/globals.js
package/contents/ui/code/utils.js
package/contents/ui/components/WidgetCardConfig.qml
package/contents/ui/components/WidgetCardOverride.qml
package/contents/ui/configPerWidget.qml
package/contents/ui/configPresetWidgetOverrides.qml
package/contents/ui/configUserWidgetOverrides.qml

- Preset overrides are linked to the current preset
- User overrides are independent and applied on top of Global settings and Preset overrides
closes: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/78

feat: User and per preset overrides

---

package/contents/ui/configPresets.qml

- Show a button to create preview for presets without one
- Click on preview to update it
closes: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/109

feat: prompt to take preview screenshot after saving preset

---

package/contents/ui/TasksModel.qml
package/contents/ui/configPresetAutoload.qml
package/contents/ui/main.qml

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/107

feat: add filter by active windows for maximized preset auto-loading

---

package/contents/config/config.qml
package/contents/ui/code/globals.js
package/contents/ui/code/utils.js
package/contents/ui/configStockPanelSettings.qml
package/contents/ui/main.qml

Makes use of the Plasma scripting API
closes: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/103

feat: allow configuring stock panel settings

---

package/contents/ui/TasksModel.qml
package/contents/ui/code/utils.js
package/contents/ui/configPresetAutoload.qml
package/contents/ui/main.qml

closes: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/132

feat: "At least one window is shown" preset auto-loading condition

---

package/contents/config/main.xml
package/contents/ui/CompactRepresentation.qml
package/contents/ui/code/enum.js
package/contents/ui/code/globals.js
package/contents/ui/configPresetAutoload.qml
package/contents/ui/main.qml

- Toggle Panel Colorizer
- Switch between selected presets
- Show popup with all presets
closes: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/135
refs: https://github.com/luisbocanegra/plasma-panel-modes-switcher/issues/5

feat: configure action on Panel Colorizer widget click

---

package/contents/ui/code/globals.js
package/contents/ui/components/FormWidgetSettings.qml
package/contents/ui/main.qml

feat: option to force always floating dialogs

---

package/contents/ui/main.qml

- dont use org.kde.KWin.reconfigure on X11 to avoid flicker, also doesn't seem to need it
- add a workaround to crash on panel location change by temporarily showing the panel, also seems to fix the activation zone being stuck at the previous screen edge
refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/160

fix: X11 screen flicker and window resizing with panel

---

package/contents/ui/DBusFallback.qml
package/contents/ui/DBusMethodCall.qml
package/contents/ui/DBusPrimary.qml
package/contents/ui/DBusServiceModel.qml
package/contents/ui/code/utils.js
package/contents/ui/main.qml

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/161

fix: fallback to gdbus for plasma 6.1

---

package/contents/ui/main.qml

fixes https://github.com/luisbocanegra/plasma-panel-colorizer/pull/164/commits/1117784271d11192abbafdd087d446658c56d4e4

fix: widget not hiding (main)

---

package/translate/zh.po

Add two translations and correct one typo

Update Chinese translation

---

package/contents/ui/configUnifiedBackground.qml

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/208

fix: unified widgets not saving sometimes

---

package/contents/ui/GradientRoundedRectangle.qml
package/contents/ui/code/globals.js
package/contents/ui/code/utils.js
package/contents/ui/components/ColorPickerGradientList.qml
package/contents/ui/components/FormColors.qml
package/contents/ui/components/FormWidgetSettings.qml
package/contents/ui/main.qml

Gradient background

---

package/contents/ui/ImageRoundedRectangle.qml
package/contents/ui/code/globals.js
package/contents/ui/components/FormColors.qml
package/contents/ui/components/FormWidgetSettings.qml
package/contents/ui/main.qml

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/128

feat: add option to use an image as background

---

package/contents/ui/code/utils.js
package/contents/ui/components/WidgetCardUnifiedBg.qml
package/contents/ui/main.qml

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/245

fix: update unfied background areas on widgets HiddenStatus

---

package/contents/ui/code/enum.js
package/contents/ui/code/globals.js
package/contents/ui/code/utils.js
package/contents/ui/components/FormBorder.qml
package/contents/ui/components/FormWidgetSettings.qml
package/contents/ui/configAppearance.qml
package/contents/ui/configGlobalWidgetOverrides.qml
package/contents/ui/configPresetWidgetOverrides.qml
package/contents/ui/main.qml

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/71
BREAKING CHANGE: Due to configuration format changes "Panel" "Widgets" "Tray widgets", "Preset/Global overrides" from existing configuration and user presets will no longer work, and need to be manually ported or recreated from scratch to the latest format

feat!: hover, expanded, needsAttention and busy customization

---

package/translate/ca.po

If there is any mistake, just let me know and I'll fix it.
Thank you!

Add Catalan translation

---

package/translate/pl.po

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/319

chore: add Polish translation

---

package/translate/uk.po

refs: https://github.com/luisbocanegra/plasma-panel-colorizer/issues/326

chore: add Ukrainian translation
